import { mkdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { registerExternalAgent, unregisterExternalAgent, listExternalAgents } from "../extensions/pi-panopticon/registry/external-registrar.js";
import { createMaildirTransport } from "../lib/transports/maildir.js";
import type { AgentRecord } from "../lib/agent-registry.js";
import type { FleetConfig } from "./config.js";
import { writeFileAtomic } from "../lib/file-persistence.js";

interface State { registrations: Record<string, string>; idempotency: Record<string, { fingerprint: string; receipt: SendReceipt }>; }
interface SendReceipt { message_id: string; accepted_at: number; state: "accepted"; correlation_id?: string; }
export class FleetError extends Error { constructor(readonly code: string, readonly retryable = false) { super(code); } }

export class FleetGateway {
  private readonly transport = createMaildirTransport();
  private state: State = { registrations: {}, idempotency: {} };
  private readonly registrarConfig;
  constructor(private readonly config: FleetConfig) { this.registrarConfig = { workspaceRoot: config.workspaceRoot, mailboxRoot: config.mailboxRoot }; }
  async init(): Promise<void> { await mkdir(this.config.stateDir, { recursive: true, mode: 0o700 }); try { this.state = JSON.parse(await readFile(join(this.config.stateDir, "state.json"), "utf8")) as State; if (!this.state || typeof this.state !== "object" || typeof this.state.registrations !== "object" || typeof this.state.idempotency !== "object") throw new Error("invalid state"); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw new FleetError("INTERNAL"); } }
  private async save(): Promise<void> { await writeFileAtomic(join(this.config.stateDir, "state.json"), `${JSON.stringify(this.state)}\n`, { mode: 0o600 }); }
  private checkWorkspace(alias: string): void { if (alias !== this.config.workspaceAlias) throw new FleetError("FORBIDDEN"); }
  async register(workspace: string, clientKey: string, displayName: string): Promise<{ agent_id: string }> { this.checkWorkspace(workspace); if (!/^[A-Za-z0-9._-]{1,128}$/.test(clientKey)) throw new FleetError("INVALID_ARGUMENT"); const existing = this.state.registrations[clientKey]; if (existing) return { agent_id: existing }; const record = await registerExternalAgent(this.registrarConfig, { name: displayName }); this.state.registrations[clientKey] = record.id; await this.save(); return { agent_id: record.id }; }
  private async own(clientKey: string): Promise<AgentRecord> { const id = this.state.registrations[clientKey]; if (!id) throw new FleetError("UNAUTHENTICATED"); const agents = await listExternalAgents(this.registrarConfig); const found = agents.find((a) => a.id === id); if (!found) throw new FleetError("FORBIDDEN"); return found; }
  async agents(workspace: string): Promise<AgentRecord[]> { this.checkWorkspace(workspace); return listExternalAgents(this.registrarConfig); }
  async send(workspace: string, clientKey: string, recipientId: string, text: string, key: string, correlationId?: string): Promise<SendReceipt> { this.checkWorkspace(workspace); const own = await this.own(clientKey); if (Buffer.byteLength(text, "utf8") > this.config.limits.maxTextBytes) throw new FleetError("INVALID_ARGUMENT"); if (!key || key.length > 256) throw new FleetError("INVALID_ARGUMENT"); const fingerprint = JSON.stringify([recipientId,text,correlationId]); const prior = this.state.idempotency[`${clientKey}:${key}`]; if (prior) { if (prior.fingerprint !== fingerprint) throw new FleetError("CONFLICT"); return prior.receipt; } const target = (await listExternalAgents(this.registrarConfig)).find((a) => a.id === recipientId); if (!target) throw new FleetError("NOT_FOUND"); const result = await this.transport.send(target, own.id, text); if (!result.accepted || !result.reference) throw new FleetError("BACKEND_UNAVAILABLE", true); const receipt: SendReceipt = { message_id: result.reference, accepted_at: Date.now(), state: "accepted", ...(correlationId ? { correlation_id: correlationId } : {}) }; this.state.idempotency[`${clientKey}:${key}`] = { fingerprint, receipt }; await this.save(); return receipt; }
  async inbox(workspace: string, clientKey: string): Promise<unknown[]> { this.checkWorkspace(workspace); const own = await this.own(clientKey); return this.transport.receive(own.id, own.mailboxPath).slice(0, this.config.limits.pageSize).map((m) => ({ message_id: m.id, sender_id: m.from, text: m.text, timestamp: m.ts, provenance: "maildir", authentication_confidence: "unknown" })); }
  async ack(workspace: string, clientKey: string, ids: string[]): Promise<Array<{ message_id: string; acknowledged: boolean }>> { this.checkWorkspace(workspace); if (ids.length > this.config.limits.maxAckIds) throw new FleetError("INVALID_ARGUMENT"); const own = await this.own(clientKey); const pending = new Set(this.transport.receive(own.id, own.mailboxPath).map((message) => message.id)); const results: Array<{ message_id: string; acknowledged: boolean }> = []; for (const id of ids) { if (!/^[A-Za-z0-9._-]+\.json$/.test(id)) throw new FleetError("INVALID_ARGUMENT"); const acknowledged = pending.has(id); if (acknowledged) this.transport.ack(own.id, id, own.mailboxPath); results.push({ message_id: id, acknowledged }); } return results; }
  async unregister(workspace: string, clientKey: string, agentId: string): Promise<void> { this.checkWorkspace(workspace); if (this.state.registrations[clientKey] !== agentId) throw new FleetError("FORBIDDEN"); await unregisterExternalAgent(this.registrarConfig, agentId); delete this.state.registrations[clientKey]; await this.save(); }
  async status(workspace: string, clientKey: string): Promise<unknown> { this.checkWorkspace(workspace); const own = await this.own(clientKey); return { backend: "maildir", connected: true, own_identity: own.id, pending: this.transport.pendingCount(own.id, own.mailboxPath), observed_at: Date.now() }; }
}
