import { describe, it, expect } from "vitest";

// Copy of TaskState from kanban.ts
interface TaskState {
	id: string;
	col: string;
	title: string;
	priority: string;
	tags: string;
	agent: string;
	claimed: boolean;
	claimAgent: string;
	expires: string;
	reason: string;
	notes: string[];
	completedAt: string;
	duration: string;
	doneAgent: string;
	createdAt: string;
}

// Copy of WIP_LIMIT from kanban.ts
const WIP_LIMIT = 3;

// Copy of BoardState interface
interface BoardState {
	tasks: Map<string, TaskState>;
	/** Insertion-ordered task IDs */
	order: string[];
	totalEvents: number;
}

// Copy of generateSnapshot function from kanban.ts (with notes rendering fix)
function generateSnapshot(board: BoardState): string {
	const { tasks, order, totalEvents } = board;
	const now = "2026-03-31T12:00:00Z";

	// Bucket by column, preserving log order
	const backlog: TaskState[] = [];
	const todo: TaskState[] = [];
	const inProgress: TaskState[] = [];
	const blocked: TaskState[] = [];
	const done: TaskState[] = [];

	for (const tid of order) {
		const t = tasks.get(tid);
		if (!t) continue;
		switch (t.col) {
			case "backlog": backlog.push(t); break;
			case "todo": todo.push(t); break;
			case "in-progress": inProgress.push(t); break;
			case "blocked": blocked.push(t); break;
			case "done": done.push(t); break;
		}
	}

	const wip = inProgress.length;
	const lines: string[] = [];

	lines.push("# CoAS Kanban — Snapshot");
	lines.push(`_Generated: ${now} | Log events: ${totalEvents} | WIP: ${wip}/${WIP_LIMIT}_`);
	lines.push("");

	// Backlog
	lines.push(`## 📋 Backlog (${backlog.length})`);
	if (backlog.length === 0) {
		lines.push("_empty_");
	} else {
		lines.push("| ID | Title | Priority | Tags |");
		lines.push("|----|-------|----------|------|");
		for (const t of backlog) {
			lines.push(`| ${t.id} | ${t.title} | ${t.priority} | ${t.tags} |`);
		}
	}
	// Render notes for backlog tasks
	for (const t of backlog) {
		if (t.notes.length > 0) {
			lines.push("");
			lines.push(`**Notes for ${t.id}:**`);
			for (const note of t.notes) {
				lines.push(`- ${note}`);
			}
		}
	}
	lines.push("");

	// Todo
	lines.push(`## 🔜 Todo (${todo.length})`);
	if (todo.length === 0) {
		lines.push("_empty_");
	} else {
		lines.push("| ID | Title | Priority | Tags |");
		lines.push("|----|-------|----------|------|");
		for (const t of todo) {
			lines.push(`| ${t.id} | ${t.title} | ${t.priority} | ${t.tags} |`);
		}
	}
	// Render notes for todo tasks
	for (const t of todo) {
		if (t.notes.length > 0) {
			lines.push("");
			lines.push(`**Notes for ${t.id}:**`);
			for (const note of t.notes) {
				lines.push(`- ${note}`);
			}
		}
	}
	lines.push("");

	// In Progress
	lines.push(`## 🔄 In Progress (${wip}/${WIP_LIMIT})`);
	if (inProgress.length === 0) {
		lines.push("_empty_");
	} else {
		lines.push("| ID | Title | Agent | Expires |");
		lines.push("|----|-------|-------|---------|");
		for (const t of inProgress) {
			lines.push(`| ${t.id} | ${t.title} | ${t.claimAgent} | ${t.expires} |`);
		}
	}
	// Render notes for in-progress tasks
	for (const t of inProgress) {
		if (t.notes.length > 0) {
			lines.push("");
			lines.push(`**Notes for ${t.id}:**`);
			for (const note of t.notes) {
				lines.push(`- ${note}`);
			}
		}
	}
	lines.push("");

	// Blocked
	lines.push(`## 🚫 Blocked (${blocked.length})`);
	if (blocked.length === 0) {
		lines.push("_empty_");
	} else {
		lines.push("| ID | Title | Reason |");
		lines.push("|----|-------|--------|");
		for (const t of blocked) {
			lines.push(`| ${t.id} | ${t.title} | ${t.reason} |`);
		}
	}
	// Render notes for blocked tasks
	for (const t of blocked) {
		if (t.notes.length > 0) {
			lines.push("");
			lines.push(`**Notes for ${t.id}:**`);
			for (const note of t.notes) {
				lines.push(`- ${note}`);
			}
		}
	}
	lines.push("");

	// Done (last 10)
	lines.push(`## ✅ Done (last 10 of ${done.length})`);
	if (done.length === 0) {
		lines.push("_empty_");
	} else {
		lines.push("| ID | Title | Agent | Completed | Duration |");
		lines.push("|----|-------|-------|-----------|----------|");
		const last10 = done.slice(-10);
		for (const t of last10) {
			lines.push(`| ${t.id} | ${t.title} | ${t.doneAgent || "—"} | ${t.completedAt || "—"} | ${t.duration || "—"} |`);
		}
	}
	// Render notes for done tasks (last 10)
	const last10Done = done.slice(-10);
	for (const t of last10Done) {
		if (t.notes.length > 0) {
			lines.push("");
			lines.push(`**Notes for ${t.id}:**`);
			for (const note of t.notes) {
				lines.push(`- ${note}`);
			}
		}
	}
	lines.push("");
	lines.push("---");
	lines.push("_Source: kanban/board.log | Read-only: do not edit this file_");

	return lines.join("\n");
}

describe("kanban generateSnapshot", () => {
	it("should render task notes in the snapshot for backlog column", () => {
		const task: TaskState = {
			id: "T-001",
			col: "backlog",
			title: "Test Task",
			priority: "high",
			tags: "test",
			agent: "test-agent",
			claimed: false,
			claimAgent: "",
			expires: "",
			reason: "",
			notes: ["2026-03-31T00:00:00Z [bob] did the thing"],
			completedAt: "",
			duration: "",
			doneAgent: "",
			createdAt: "2026-03-31T00:00:00Z",
		};

		const board: BoardState = {
			tasks: new Map([["T-001", task]]),
			order: ["T-001"],
			totalEvents: 1,
		};

		const snapshot = generateSnapshot(board);
		expect(snapshot).toContain("**Notes for T-001:**");
		expect(snapshot).toContain("2026-03-31T00:00:00Z [bob] did the thing");
	});

	it("should render task notes for todo column", () => {
		const task: TaskState = {
			id: "T-002",
			col: "todo",
			title: "Todo Task",
			priority: "medium",
			tags: "test",
			agent: "test-agent",
			claimed: false,
			claimAgent: "",
			expires: "",
			reason: "",
			notes: ["2026-03-31T01:00:00Z [alice] started work"],
			completedAt: "",
			duration: "",
			doneAgent: "",
			createdAt: "2026-03-31T00:00:00Z",
		};

		const board: BoardState = {
			tasks: new Map([["T-002", task]]),
			order: ["T-002"],
			totalEvents: 1,
		};

		const snapshot = generateSnapshot(board);
		expect(snapshot).toContain("**Notes for T-002:**");
		expect(snapshot).toContain("2026-03-31T01:00:00Z [alice] started work");
	});

	it("should render task notes for in-progress column", () => {
		const task: TaskState = {
			id: "T-003",
			col: "in-progress",
			title: "In Progress Task",
			priority: "critical",
			tags: "test",
			agent: "test-agent",
			claimed: true,
			claimAgent: "worker",
			expires: "2026-03-31T02:00:00Z",
			reason: "",
			notes: ["2026-03-31T01:30:00Z [worker] core logic done"],
			completedAt: "",
			duration: "",
			doneAgent: "",
			createdAt: "2026-03-31T00:00:00Z",
		};

		const board: BoardState = {
			tasks: new Map([["T-003", task]]),
			order: ["T-003"],
			totalEvents: 1,
		};

		const snapshot = generateSnapshot(board);
		expect(snapshot).toContain("**Notes for T-003:**");
		expect(snapshot).toContain("2026-03-31T01:30:00Z [worker] core logic done");
	});

	it("should render task notes for blocked column", () => {
		const task: TaskState = {
			id: "T-004",
			col: "blocked",
			title: "Blocked Task",
			priority: "high",
			tags: "test",
			agent: "test-agent",
			claimed: false,
			claimAgent: "",
			expires: "",
			reason: "waiting for dependency",
			notes: ["2026-03-31T02:00:00Z [worker] waiting on API key"],
			completedAt: "",
			duration: "",
			doneAgent: "",
			createdAt: "2026-03-31T00:00:00Z",
		};

		const board: BoardState = {
			tasks: new Map([["T-004", task]]),
			order: ["T-004"],
			totalEvents: 1,
		};

		const snapshot = generateSnapshot(board);
		expect(snapshot).toContain("**Notes for T-004:**");
		expect(snapshot).toContain("2026-03-31T02:00:00Z [worker] waiting on API key");
	});

	it("should render task notes for done column", () => {
		const task: TaskState = {
			id: "T-005",
			col: "done",
			title: "Completed Task",
			priority: "medium",
			tags: "test",
			agent: "test-agent",
			claimed: false,
			claimAgent: "",
			expires: "",
			reason: "",
			notes: ["2026-03-31T03:00:00Z [worker] testing complete"],
			completedAt: "2026-03-31T03:30:00Z",
			duration: "30m",
			doneAgent: "worker",
			createdAt: "2026-03-31T00:00:00Z",
		};

		const board: BoardState = {
			tasks: new Map([["T-005", task]]),
			order: ["T-005"],
			totalEvents: 1,
		};

		const snapshot = generateSnapshot(board);
		expect(snapshot).toContain("**Notes for T-005:**");
		expect(snapshot).toContain("2026-03-31T03:00:00Z [worker] testing complete");
	});

	it("should not render notes section when task has no notes", () => {
		const task: TaskState = {
			id: "T-006",
			col: "todo",
			title: "Task without notes",
			priority: "low",
			tags: "test",
			agent: "test-agent",
			claimed: false,
			claimAgent: "",
			expires: "",
			reason: "",
			notes: [],
			completedAt: "",
			duration: "",
			doneAgent: "",
			createdAt: "2026-03-31T00:00:00Z",
		};

		const board: BoardState = {
			tasks: new Map([["T-006", task]]),
			order: ["T-006"],
			totalEvents: 1,
		};

		const snapshot = generateSnapshot(board);
		expect(snapshot).not.toContain("**Notes for T-006:**");
	});

	it("should render multiple notes for a single task", () => {
		const task: TaskState = {
			id: "T-007",
			col: "in-progress",
			title: "Task with multiple notes",
			priority: "high",
			tags: "test",
			agent: "test-agent",
			claimed: true,
			claimAgent: "worker",
			expires: "2026-03-31T04:00:00Z",
			reason: "",
			notes: [
				"2026-03-31T01:00:00Z [worker] started",
				"2026-03-31T02:00:00Z [worker] debugging",
				"2026-03-31T03:00:00Z [worker] almost done",
			],
			completedAt: "",
			duration: "",
			doneAgent: "",
			createdAt: "2026-03-31T00:00:00Z",
		};

		const board: BoardState = {
			tasks: new Map([["T-007", task]]),
			order: ["T-007"],
			totalEvents: 1,
		};

		const snapshot = generateSnapshot(board);
		expect(snapshot).toContain("**Notes for T-007:**");
		expect(snapshot).toContain("2026-03-31T01:00:00Z [worker] started");
		expect(snapshot).toContain("2026-03-31T02:00:00Z [worker] debugging");
		expect(snapshot).toContain("2026-03-31T03:00:00Z [worker] almost done");
	});
});
