/**
 * Kanban snapshot renderer.
 *
 * Generates a Markdown snapshot from BoardState — pure functions
 * with no side effects. The snapshot tool writes the result to disk.
 */

import type { BoardState, TaskState } from "./board.js";
import { WIP_LIMIT, nowZ } from "./board.js";

// ── Column definitions ──────────────────────────────────────────

interface ColumnDef {
	heading: string;
	headers: string[];
	separators: string[];
	row: (t: TaskState) => string;
}

const PRIO_COL_ROW = (t: TaskState) => `| ${t.id} | ${t.title} | ${t.priority} | ${t.tags} |`;

const PRIO_COL_HDR: ColumnDef = {
	heading: "",
	headers: ["| ID | Title | Priority | Tags |"],
	separators: ["|----|-------|----------|------|"],
	row: PRIO_COL_ROW,
};

const COLUMN_DEFS: Record<string, ColumnDef> = {
	backlog: { ...PRIO_COL_HDR, heading: "📋 Backlog" },
	todo: { ...PRIO_COL_HDR, heading: "🔜 Todo" },
	"in-progress": {
		heading: "🔄 In Progress",
		headers: ["| ID | Title | Agent | Model | Expires |"],
		separators: ["|----|-------|-------|-------|---------|"],
		row: (t) => `| ${t.id} | ${t.title} | ${t.claimAgent} | ${t.model || "—"} | ${t.expires} |`,
	},
	blocked: {
		heading: "🚫 Blocked",
		headers: ["| ID | Title | Reason |"],
		separators: ["|----|-------|--------|"],
		row: (t) => `| ${t.id} | ${t.title} | ${t.reason} |`,
	},
	done: {
		heading: "✅ Done",
		headers: ["| ID | Title | Agent | Completed | Duration |"],
		separators: ["|----|-------|-------|-----------|----------|"],
		row: (t) => `| ${t.id} | ${t.title} | ${t.doneAgent || "—"} | ${t.completedAt || "—"} | ${t.duration || "—"} |`,
	},
};

// ── Rendering ───────────────────────────────────────────────────

/** Render a single column section: heading, table, and notes. */
function renderColumn(tasks: TaskState[], colKey: string, countLabel: string): string[] {
	const def = COLUMN_DEFS[colKey];
	if (!def) return [];
	const lines: string[] = [];

	lines.push(`## ${def.heading} (${countLabel})`);
	if (tasks.length === 0) {
		lines.push("_empty_");
	} else {
		lines.push(...def.headers, ...def.separators);
		for (const t of tasks) lines.push(def.row(t));
	}

	for (const t of tasks.filter((t) => t.description || t.notes.length > 0)) {
		const noteBullets: string[] = [];
		if (t.description) noteBullets.push(`- Description: ${t.description}`);
		noteBullets.push(...t.notes.map((n) => `- ${n}`));
		lines.push("", `**Notes for ${t.id}:**`, ...noteBullets);
	}
	lines.push("");
	return lines;
}

/** Generate a full Markdown snapshot from parsed board state. */
export function generateSnapshot(board: BoardState): string {
	const { tasks, order, totalEvents } = board;
	const now = nowZ();

	const buckets: Record<string, TaskState[]> = {
		backlog: [], todo: [], "in-progress": [], blocked: [], done: [],
	};
	for (const tid of order) {
		const t = tasks.get(tid);
		if (!t || t.deleted) continue;
		buckets[t.col]?.push(t);
	}

	const wip = buckets["in-progress"]?.length ?? 0;
	const doneAll = buckets.done ?? [];
	const doneLast10 = doneAll.slice(-10);

	return [
		"# CoAS Kanban — Snapshot",
		`_Generated: ${now} | Log events: ${totalEvents} | WIP: ${wip}/${WIP_LIMIT}_`,
		"",
		...renderColumn(buckets.backlog ?? [], "backlog", String(buckets.backlog?.length ?? 0)),
		...renderColumn(buckets.todo ?? [], "todo", String(buckets.todo?.length ?? 0)),
		...renderColumn(buckets["in-progress"] ?? [], "in-progress", `${wip}/${WIP_LIMIT}`),
		...renderColumn(buckets.blocked ?? [], "blocked", String(buckets.blocked?.length ?? 0)),
		...renderColumn(doneLast10, "done", `last 10 of ${doneAll.length}`),
		"---",
		"_Source: kanban/board.log | Read-only: do not edit this file_",
	].join("\n");
}
